### ISSUE TITLE
 android of support is difficult ?

### ISSUE THREAD

**Issue by kimukou** [basilisk-fw/basilisk#2]
> lazybones create basilisk-javafx-ios sample

after edit build.gradle

- build.gradle
```build.gradle
jfxmobile {
    ios {
        forceLinkClasses = ['org.example.**.*', 'basilisk.**.*', 'org.kordamp.basilisk.**.*']
    }
	android {
        applicationPackage = 'org.example'
    }
}

retrolambda {
    jdk '/usr/libexec/java_home -v 1.8'.execute().text
    oldJdk '/usr/libexec/java_home -v 1.7'.execute().text
     javaVersion JavaVersion.VERSION_1_7
} 
```

> gradlew tasks
>  gradlew android

but stack error occuerd

```error.log
:createMainDexList FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':createMainDexList'.
> Picked up _JAVA_OPTIONS: -Dfile.encoding=UTF-8 -Dgroovy.source.encoding=UTF-8
  Exception in thread "main" com.android.dx.cf.iface.ParseException: InvokeDynamic not supported
  	at com.android.dx.cf.cst.ConstantPoolParser.determineOffsets(ConstantPoolParser.java:226)
  	at com.android.dx.cf.cst.ConstantPoolParser.parse(ConstantPoolParser.java:132)
  	at com.android.dx.cf.cst.ConstantPoolParser.parseIfNecessary(ConstantPoolParser.java:124)
  	at com.android.dx.cf.cst.ConstantPoolParser.getPool(ConstantPoolParser.java:115)
  	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:482)
  	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
  	at com.android.dx.cf.direct.DirectClassFile.parseToEndIfNecessary(DirectClassFile.java:397)
  	at com.android.dx.cf.direct.DirectClassFile.getAttributes(DirectClassFile.java:311)
  	at com.android.multidex.MainDexListBuilder.hasRuntimeVisibleAnnotation(MainDexListBuilder.java:191)
  	at com.android.multidex.MainDexListBuilder.keepAnnotated(MainDexListBuilder.java:167)
  	at com.android.multidex.MainDexListBuilder.<init>(MainDexListBuilder.java:121)
  	at com.android.multidex.MainDexListBuilder.main(MainDexListBuilder.java:91)
  	at com.android.multidex.ClassReferenceListBuilder.main(ClassReferenceListBuilder.java:58)
  ...while preparsing cst 0005 at offset 0000001a
  ...while parsing org/kordamp/basilisk/runtime/core/controller/DefaultAction.class
```

Please advice whether may be modified.

**Comment by aalmiray** [comment]
I think the Basilisk classes did not go through the retrolambda process. DefaultAction must be making use of lambda expressions, which rely on InvokeDynamic to work. applying retrolambda to Basilisk dependencies should fix the problem.
